name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  powershell-security:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer
        run: |
          $results = Invoke-ScriptAnalyzer -Path . -Recurse
          if ($results.Count -gt 0) {
            $results | Format-Table | Out-String | Write-Host
            exit 1
          }
